pipeline {
agent any
	stages {
		stage ('clean') {
			steps {
				sh 'mvn clean'
			}
		}
		stage ('build') {
			steps {
				sh 'mvn compile'
			}
		}
		stage ('package') {
			steps {
				sh 'mvn package'
			}
		}
	}
}
